# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carousel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=200, verbose_name='\u90ae\u7bb1')),
                ('img', models.CharField(default='/static/img/head/default.jpeg', max_length=200, verbose_name='\u7528\u6237\u5934\u50cf')),
            ],
        ),
    ]
