# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161220_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='\u7528\u9017\u53f7\u5206\u9694', max_length=200, null=True, to='blog.Tags', verbose_name='\u6807\u7b7e'),
        ),
    ]
